import { describe, it, expect } from 'vitest';
import { signJwt, verifyJwt, verifyEd25519Signature } from '../auth';
import * as nodeCrypto from 'crypto';

describe('Admin Worker Auth Utilities', () => {
  const SECRET = 'test_secret_key_for_jwt_signing';
  
  it('signs and verifies a standard payload successfully', async () => {
    const payload = { type: 'session', admin_id: 'ad_1234' };
    
    const token = await signJwt(payload, SECRET, 3600); // 1 hour
    expect(token.split('.').length).toBe(3);
    
    const decoded = await verifyJwt(token, SECRET);
    expect(decoded.type).toBe('session');
    expect(decoded.admin_id).toBe('ad_1234');
    expect(decoded.exp).toBeDefined();
    expect(decoded.iat).toBeDefined();
  });

  it('fails verification if the JWT is signed with a different secret', async () => {
    const token = await signJwt({ data: 'secret' }, SECRET, 3600);
    
    await expect(verifyJwt(token, 'totally_wrong_secret')).rejects.toThrow('Invalid JWT signature');
  });

  it('fails verification if the token has expired', async () => {
    const token = await signJwt({ data: 'expired' }, SECRET, -100); // Expires in the past
    
    await expect(verifyJwt(token, SECRET)).rejects.toThrow('JWT expired');
  });

  it('fails verification if the token structure is corrupted', async () => {
    await expect(verifyJwt('header.payloadWithoutSignature', SECRET)).rejects.toThrow('Invalid token structure');
    await expect(verifyJwt('randomgibberish', SECRET)).rejects.toThrow('Invalid token structure');
  });

  it('verifies Ed25519 signatures generated by Node crypto correctly', async () => {
    const { publicKey, privateKey } = nodeCrypto.generateKeyPairSync('ed25519');
    const pubKeyPem = publicKey.export({ type: 'spki', format: 'pem' }) as string;
    
    const dataToSign = 'hello world nonce 123';
    
    const signature = nodeCrypto.sign(null, Buffer.from(dataToSign, 'utf8'), privateKey);
    const signatureB64 = signature.toString('base64url');
    
    const isValid = await verifyEd25519Signature(pubKeyPem, signatureB64, dataToSign);
    expect(isValid).toBe(true);
    
    const isValidWrongData = await verifyEd25519Signature(pubKeyPem, signatureB64, 'wrong data');
    expect(isValidWrongData).toBe(false);
  });
});
